"use client";
import { useEffect,useMemo,useState } from "react";import { BookOpenCheck,Search } from "lucide-react";import { defaultNetworkAccounts,MESSAGE_DRAFTS_KEY,NETWORK_ACCOUNTS_KEY } from "@/lib/network/data";import { networkAccountsSchema } from "@/lib/network/schema";import type { DebtTone,NetworkAccount } from "@/lib/network/types";import type { DebtCollectorResult } from "@/lib/network/schema";import { readValidated,writeVersioned } from "@/lib/storage";import { calculateNetworkBalance } from "@/lib/network/calculate";import { CollectionSummary } from "./collection-summary";import { NetworkAccountCard } from "@/components/network/network-account-card";import { AccountDrawer } from "@/components/network/account-drawer";import { Toast } from "@/components/shared/toast";
const filters=["All accounts","They owe you","You owe them","Balanced","Overdue","Ghosted"] as const;type Filter=typeof filters[number];
export function Collections(){const [accounts,setAccounts]=useState<NetworkAccount[]>(defaultNetworkAccounts);const [ready,setReady]=useState(false);const [filter,setFilter]=useState<Filter>("All accounts");const [query,setQuery]=useState("");const [selectedId,setSelectedId]=useState<string|null>(null);const [toast,setToast]=useState("");
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setAccounts(readValidated(NETWORK_ACCOUNTS_KEY,networkAccountsSchema,defaultNetworkAccounts));setReady(true)},[]);useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),2500);return()=>clearTimeout(id)},[toast]);
 const shown=useMemo(()=>accounts.filter(a=>{const b=calculateNetworkBalance(a);const matches=filter==="All accounts"||filter==="They owe you"&&b.direction==="they_owe_you"||filter==="You owe them"&&b.direction==="you_owe_them"||filter==="Balanced"&&b.direction==="balanced"||filter==="Overdue"&&b.overdueCount>0||filter==="Ghosted"&&b.ghostingRisk==="high";return matches&&a.person.name.toLowerCase().includes(query.toLowerCase())}),[accounts,filter,query]);const selected=accounts.find(a=>a.id===selectedId)||null;
 function update(account:NetworkAccount){const next=accounts.map(a=>a.id===account.id?account:a);setAccounts(next);writeVersioned(NETWORK_ACCOUNTS_KEY,next)}function saveDraft(result:DebtCollectorResult,tone:DebtTone,account:NetworkAccount){let existing:unknown[]=[];try{existing=JSON.parse(localStorage.getItem(MESSAGE_DRAFTS_KEY)||"[]")}catch{}writeVersioned(MESSAGE_DRAFTS_KEY,[{id:`d-${Date.now()}`,accountId:account.id,recipient:account.person.name,tone,result,savedAt:new Date().toISOString()},...existing].slice(0,20))}
 if(!ready)return <main className="shell py-8"><div className="card h-80 animate-pulse"/></main>;
 return <><main className="shell py-5 sm:py-8"><header className="mb-5 flex items-start gap-3"><span className="grid h-11 w-11 place-items-center rounded-lg bg-[#e8f3ff] text-[#0A66C2]"><BookOpenCheck/></span><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-[#0A66C2]">Relationship ledger</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Network Accounts</h1><p className="mt-1 text-[12px] text-[#666]">Your professional favour economy, audited by an AI with no social life.</p></div></header><CollectionSummary accounts={accounts}/><section className="card mt-4 overflow-hidden"><div className="flex flex-col gap-3 border-b border-[#ddd] p-4 sm:flex-row sm:items-center"><div className="flex gap-1 overflow-x-auto pb-1">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-[10px] font-bold ${filter===f?"bg-[#191919] text-white":"bg-[#eee] text-[#555]"}`}>{f}</button>)}</div><label className="relative sm:ml-auto"><span className="sr-only">Search accounts</span><Search size={14} className="absolute left-3 top-1/2 -translate-y-1/2 text-[#777]"/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search accounts" className="w-full rounded-full border border-[#aaa] py-1.5 pl-9 pr-3 text-[11px] sm:w-44"/></label></div><div className="grid gap-3 bg-[#f6f5f2] p-3 sm:grid-cols-2">{shown.map(a=><NetworkAccountCard key={a.id} account={a} onOpen={()=>setSelectedId(a.id)}/>)}{!shown.length&&<div className="col-span-2 p-8 text-center text-[12px] text-[#666]">No accounts fit this audit. The spreadsheet is briefly at peace.</div>}</div></section><p className="mx-auto mt-4 max-w-2xl text-center text-[10px] leading-4 text-[#777]">For satire and reflection. Human relationships are not financial accounts, despite what the spreadsheet suggests. Drafts are never sent automatically.</p></main><AccountDrawer account={selected} onClose={()=>setSelectedId(null)} onUpdate={update} onSaveDraft={saveDraft} onToast={setToast}/><Toast message={toast} onClose={()=>setToast("")}/></>}
