"use client";
import { useEffect,useMemo,useState } from "react";import { FileCheck2,FileQuestion,RotateCcw,Scale,Users } from "lucide-react";import { defaultEndorsements,ENDORSEMENTS_KEY,ENDORSEMENT_REVIEWS_KEY,mockEndorsers,profileSkills } from "@/lib/endorsements/data";import { endorsementReviewsSchema,endorsementsSchema } from "@/lib/endorsements/schema";import type { EndorsementRecordState,SkillEndorsement } from "@/lib/endorsements/types";import { readValidated,writeVersioned } from "@/lib/storage";import { EndorsementCaseCard } from "./endorsement-case-card";import { EndorsementCaseDrawer } from "./endorsement-case-drawer";import { currentClientStamp } from "@/lib/client-values";import { Toast } from "@/components/shared/toast";
const filters=["All","Verified","Supported","Partial","Vague","Unreviewed"] as const;type Filter=typeof filters[number];
export function CrossExaminer(){const [endorsements,setEndorsements]=useState<SkillEndorsement[]>(defaultEndorsements);const [records,setRecords]=useState<Record<string,EndorsementRecordState>>({});const [filter,setFilter]=useState<Filter>("All");const [selected,setSelected]=useState<string|null>(null);const [ready,setReady]=useState(false);const [toast,setToast]=useState("");
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setEndorsements(readValidated(ENDORSEMENTS_KEY,endorsementsSchema,defaultEndorsements));setRecords(readValidated(ENDORSEMENT_REVIEWS_KEY,endorsementReviewsSchema,{}));setReady(true)},[]);useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(id)},[toast]);const shown=useMemo(()=>endorsements.filter(e=>!records[e.id]?.archived&&(filter==="All"||filter==="Verified"&&e.verdict?.status==="verified"||filter==="Supported"&&e.verdict?.status==="supported"||filter==="Partial"&&e.verdict?.status==="partially_supported"||filter==="Vague"&&e.verdict?.status==="vague"||filter==="Unreviewed"&&!e.verdict)),[endorsements,records,filter]);const active=endorsements.find(e=>e.id===selected)||null;const skill=active?profileSkills.find(s=>s.id===active.skillId)||null:null;
 function setRecord(r:EndorsementRecordState){if(!active)return;const next={...records,[active.id]:r};setRecords(next);writeVersioned(ENDORSEMENT_REVIEWS_KEY,next);setToast(r.archived?"Case archived locally.":r.reviewRequested?"Evidence request recorded. Nothing was sent.":"Review accepted locally.")}
 async function rerun(e:SkillEndorsement){const sk=profileSkills.find(s=>s.id===e.skillId)!;const res=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({feature:"endorsementCrossExaminer",data:{skill:sk,endorsement:e}})});const body=await res.json();const next=endorsements.map(x=>x.id===e.id?{...x,verdict:body.result}:x);setEndorsements(next);writeVersioned(ENDORSEMENTS_KEY,next);setToast(body.demo?"Case reviewed with demo logic.":"Case reviewed by the evidence desk.")}
 function createMock(){const now=currentClientStamp();const e:SkillEndorsement={id:`mock-${now.id}`,skillId:"product-design",candidateId:"khushal",endorser:mockEndorsers[4],submittedAt:now.iso,answers:{personallyObserved:false,contributionDescription:"Khushal has good product instincts and makes useful things.",evidenceType:"none",confidence:"supportive_but_unsure"}};const next=[e,...endorsements];setEndorsements(next);writeVersioned(ENDORSEMENTS_KEY,next);setToast("A friendly unreviewed endorsement entered the docket.")}
 function reset(){setEndorsements(defaultEndorsements);setRecords({});writeVersioned(ENDORSEMENTS_KEY,defaultEndorsements);writeVersioned(ENDORSEMENT_REVIEWS_KEY,{});setToast("Endorsement demo reset.")}
 if(!ready)return <main className="shell py-8"><div className="card h-80 animate-pulse"/></main>;const verified=endorsements.filter(e=>e.verdict?.status==="verified").length,vague=endorsements.filter(e=>e.verdict?.status==="vague"||e.verdict?.status==="unverified").length;return <><main className="shell py-5 sm:py-8"><header className="mb-5 flex gap-3"><span className="grid h-11 w-11 place-items-center rounded-lg bg-[#edf3f8] text-[#0A66C2]"><Scale/></span><div><p className="text-[10px] font-bold uppercase tracking-[.15em] text-[#0A66C2]">Evidence desk</p><h1 className="text-2xl font-bold tracking-tight sm:text-3xl">Endorsement Review</h1><p className="mt-1 text-[12px] text-[#666]">Because clicking a skill button should require slightly more evidence than friendship.</p></div></header><div className="grid grid-cols-2 gap-3 md:grid-cols-4"><Summary Icon={Users} value={endorsements.length} label="Total endorsements"/><Summary Icon={FileCheck2} value={verified} label="Verified"/><Summary Icon={FileQuestion} value={vague} label="Vague testimony"/><Summary Icon={Scale} value={endorsements.filter(e=>!records[e.id]?.accepted).length} label="Awaiting acceptance"/></div><section className="mt-4"><div className="card flex flex-col gap-3 p-3 sm:flex-row sm:items-center"><div className="flex gap-1 overflow-x-auto">{filters.map(f=><button key={f} onClick={()=>setFilter(f)} className={`whitespace-nowrap rounded-full px-3 py-1.5 text-[10px] font-bold ${filter===f?"bg-[#191919] text-white":"bg-[#eee]"}`}>{f}</button>)}</div><div className="flex gap-3 sm:ml-auto"><button onClick={createMock} className="text-[10px] font-bold text-[#0A66C2]">+ Create mock endorsement</button><button onClick={reset} className="flex items-center gap-1 text-[10px] font-bold text-[#777]"><RotateCcw size={12}/>Reset</button></div></div><div className="mt-3 grid gap-3 sm:grid-cols-2">{shown.map(e=><EndorsementCaseCard key={e.id} endorsement={e} skill={profileSkills.find(s=>s.id===e.skillId)!} onOpen={()=>setSelected(e.id)}/>)}</div></section></main><EndorsementCaseDrawer endorsement={active} skill={skill} record={active?records[active.id]||{}:{}} onClose={()=>setSelected(null)} onRecord={setRecord} onRerun={rerun}/><Toast message={toast} onClose={()=>setToast("")}/></>}
function Summary({Icon,value,label}:{Icon:typeof Users;value:number;label:string}){return <section className="card p-4"><Icon size={17} className="text-[#0A66C2]"/><b className="mt-2 block text-xl">{value}</b><p className="text-[9px] uppercase tracking-wider text-[#777]">{label}</p></section>}
