"use client";
import { Leaf,RefreshCw,Sparkles } from "lucide-react";import type { CareerActivity,CareerPlantState } from "@/lib/career/types";import type { CareerGardenerResult } from "@/lib/career/schema";
export function CareerGardenerPanel({activity,state}:{activity:CareerActivity;state:CareerPlantState}){const [result,setResult]=React.useState<CareerGardenerResult|null>(null);const [loading,setLoading]=React.useState(false);const [demo,setDemo]=React.useState(false);const [error,setError]=React.useState("");
 async function ask(){setLoading(true);setError("");try{const res=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({feature:"careerGardener",data:{activity,plantState:state}})});const body=await res.json();if(!res.ok)throw new Error(body.error);setResult(body.result);setDemo(body.demo)}catch{setError("The gardener is repotting. Try once more.")}finally{setLoading(false)}}
 return <section className="card p-5"><div className="flex items-start justify-between"><div><p className="flex items-center gap-2 text-[11px] font-bold uppercase tracking-wider text-[#39734a]"><Leaf size={14}/>Career gardener</p><h2 className="mt-2 text-lg font-semibold">Specific advice, lightly composted.</h2></div>{demo&&<span className="rounded-full border border-[#bad0b7] bg-[#f0f8ee] px-2 py-1 text-[9px] font-bold text-[#3f6c42]">DEMO ADVICE</span>}</div>
 {loading?<div className="my-7 text-center"><Leaf className="mx-auto animate-pulse text-[#4c8452]"/><p className="mt-3 text-[12px] text-[#666]">Inspecting your roots…</p></div>:result?<div className="mt-4 space-y-4"><div className="rounded-lg bg-[#f4f8f2] p-4"><h3 className="font-semibold">{result.headline}</h3><p className="mt-1 text-[12px] leading-5 text-[#555]">{result.interpretation}</p></div><div className="grid gap-2 sm:grid-cols-2"><Info label="Strongest area" text={result.strongestArea}/><Info label="Needs attention" text={result.neglectedArea}/></div><div><h3 className="mb-2 text-[12px] font-bold">Suggested next actions</h3>{result.nextActions.map(a=><div key={a.title} className="mb-2 flex justify-between gap-3 rounded-lg border border-[#e2e4df] p-3"><div><b className="text-[12px]">{a.title}</b><p className="text-[11px] leading-4 text-[#666]">{a.reason}</p></div><span className="h-fit rounded-full bg-[#eef3f8] px-2 py-1 text-[9px] font-bold uppercase">{a.difficulty}</span></div>)}</div><p className="border-l-2 border-[#5f8b64] pl-3 text-[12px] italic text-[#555]">{result.gardenMetaphor}</p></div>:<p className="my-5 text-[12px] leading-5 text-[#666]">Get a concise reading of your strongest branch, shallowest roots, and three useful next moves.</p>}
 {error&&<p className="mt-3 text-[12px] text-[#B24020]">{error}</p>}<button onClick={ask} disabled={loading} className="primary-button mt-4 flex items-center gap-2 text-[12px]">{result?<RefreshCw size={14}/>:<Sparkles size={14}/>} {result?"Refresh advice":"Ask the career gardener"}</button></section>}
function Info({label,text}:{label:string;text:string}){return <div className="rounded-lg border border-[#e1e1de] p-3"><p className="text-[9px] font-bold uppercase tracking-wider text-[#777]">{label}</p><p className="mt-1 text-[12px] font-semibold">{text}</p></div>}
import * as React from "react";
