"use client";
import { useEffect,useMemo,useState } from "react";import { BadgeCheck,BookOpen,FolderPlus,HeartHandshake,Leaf,MessageSquareText,RotateCcw,Sprout } from "lucide-react";import { CareerPlantSvg,type PlantSelection } from "./career-plant-svg";import { PlantInspector } from "./plant-inspector";import { CareerGardenerPanel } from "./career-gardener-panel";import { GrowthTimeline } from "./growth-timeline";import { calculateCareerPlant } from "@/lib/career/calculate";import { CAREER_ACTIVITY_KEY,defaultCareerActivity,defaultGrowthHistory,GROWTH_HISTORY_KEY } from "@/lib/career/data";import { careerActivitySchema,growthHistorySchema } from "@/lib/career/schema";import type { CareerActivity,GrowthEntry } from "@/lib/career/types";import { readValidated,writeVersioned } from "@/lib/storage";import { Toast } from "@/components/shared/toast";import { currentClientStamp } from "@/lib/client-values";
const actions=[{id:"project",label:"Complete a project",Icon:FolderPlus},{id:"skill",label:"Add a skill",Icon:Leaf},{id:"verify",label:"Verify a skill",Icon:BadgeCheck},{id:"endorse",label:"Receive endorsement",Icon:HeartHandshake},{id:"post",label:"Publish helpful post",Icon:MessageSquareText},{id:"learn",label:"Record learning day",Icon:BookOpen}] as const;
export function Greenhouse(){const [activity,setActivity]=useState<CareerActivity>(defaultCareerActivity);const [history,setHistory]=useState<GrowthEntry[]>(defaultGrowthHistory);const [ready,setReady]=useState(false);const [selection,setSelection]=useState<PlantSelection|null>(null);const [toast,setToast]=useState("");const [highlight,setHighlight]=useState("");const state=useMemo(()=>calculateCareerPlant(activity),[activity]);
 // localStorage is intentionally loaded after hydration.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{setActivity(readValidated(CAREER_ACTIVITY_KEY,careerActivitySchema,defaultCareerActivity));setHistory(readValidated(GROWTH_HISTORY_KEY,growthHistorySchema,defaultGrowthHistory));setReady(true)},[]);
 useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),2400);return()=>clearTimeout(id)},[toast]);
 function commit(next:CareerActivity,text:string,type:GrowthEntry["type"],mark:string){const now=currentClientStamp();const entry={id:`g-${now.id}`,date:now.iso,text,type};const nextHistory=[entry,...history];setActivity(next);setHistory(nextHistory);writeVersioned(CAREER_ACTIVITY_KEY,next);writeVersioned(GROWTH_HISTORY_KEY,nextHistory);setToast(text);setHighlight(mark);setTimeout(()=>setHighlight(""),1000)}
 function simulate(id:typeof actions[number]["id"]){const now=currentClientStamp();if(id==="project")return commit({...activity,completedProjects:[...activity.completedProjects,{id:`p-${now.id}`,name:"Signal Dock",category:"backend",completedAt:now.iso,significance:2}]},"A new backend branch formed.","project","branch");if(id==="skill")return commit({...activity,skills:[...activity.skills,{id:`docker-${now.id}`,name:"Docker",category:"backend",verified:false,evidenceCount:1}]},"A new leaf grew for Docker.","skill","skill");if(id==="verify"){const index=activity.skills.findIndex(s=>!s.verified);if(index<0)return setToast("Every current skill is already verified.");const skills=activity.skills.map((s,i)=>i===index?{...s,verified:true}:s);return commit({...activity,skills},`${skills[index].name} grew into a verified leaf.`,"verification","skill")}if(id==="endorse")return commit({...activity,endorsements:[...activity.endorsements,{id:`e-${now.id}`,skillId:activity.skills[0]?.id||"general",verified:true}]},"Your roots strengthened after a verified endorsement.","endorsement","roots");if(id==="post")return commit({...activity,helpfulPosts:activity.helpfulPosts+1},"A helpful post produced a new shoot.","post","skill");return commit({...activity,learningDaysLast30:Math.min(30,activity.learningDaysLast30+1)},"One calm learning day improved plant health.","learning","stem")}
 function reset(){setActivity(defaultCareerActivity);setHistory(defaultGrowthHistory);writeVersioned(CAREER_ACTIVITY_KEY,defaultCareerActivity);writeVersioned(GROWTH_HISTORY_KEY,defaultGrowthHistory);setToast("Career garden reset to the demo profile.")}
 if(!ready)return <div className="shell py-8"><div className="card h-[500px] animate-pulse bg-[#eef2eb]"/></div>;
 return <><main className="shell py-5 sm:py-8"><header className="mb-5"><p className="text-[11px] font-bold uppercase tracking-[.16em] text-[#39734a]">Khushal’s career garden</p><h1 className="mt-1 text-2xl font-bold tracking-tight sm:text-3xl">The Greenhouse</h1><p className="mt-2 max-w-2xl text-[13px] leading-5 text-[#666]">A living view of skills, evidence, projects, and professional momentum. No streaks, guilt, or endangered houseplants.</p></header><div className="grid gap-5 lg:grid-cols-[minmax(0,620px)_minmax(320px,1fr)]"><div className="space-y-4"><section className="card overflow-hidden"><div className="flex items-center justify-between border-b border-[#e3e5e0] px-5 py-3"><div><h2 className="font-semibold capitalize">{state.status} · Level {state.overallLevel}</h2><p className="text-[11px] text-[#666]">Select any plant element to inspect it.</p></div><span className="rounded-full bg-[#edf6eb] px-3 py-1 text-[11px] font-bold text-[#39734a]">{state.healthScore}% healthy</span></div><div className="bg-[linear-gradient(180deg,#f5f9f2,#fbf7ed)] px-3"><CareerPlantSvg activity={activity} state={state} onSelect={setSelection} highlight={highlight}/></div><div className="p-4"><PlantInspector selection={selection} onClose={()=>setSelection(null)}/></div></section><GrowthTimeline entries={history}/></div><aside className="space-y-4"><PlantStatus activity={activity}/><CareerGardenerPanel activity={activity} state={state}/><section className="card p-5"><div className="flex items-center gap-2"><Sprout size={18} className="text-[#39734a]"/><h2 className="font-semibold">Simulate professional growth</h2></div><p className="mt-1 text-[11px] leading-4 text-[#666]">Prototype controls update this plant and save locally.</p><div className="mt-4 grid grid-cols-2 gap-2">{actions.map(({id,label,Icon})=><button key={id} onClick={()=>simulate(id)} className="flex min-h-12 items-center gap-2 rounded-lg border border-[#d8ddd5] px-3 text-left text-[11px] font-semibold hover:bg-[#f3f7f1]"><Icon size={16} className="text-[#39734a]"/>{label}</button>)}</div><button onClick={reset} className="mt-3 flex items-center gap-2 text-[11px] font-bold text-[#666] hover:text-[#B24020]"><RotateCcw size={14}/>Reset demo growth</button></section></aside></div></main><Toast message={toast} onClose={()=>setToast("")}/></>}
function PlantStatus({activity}:{activity:CareerActivity}){const s=calculateCareerPlant(activity);return <section className="card p-5"><h2 className="font-semibold">Growth summary</h2><div className="mt-4 grid grid-cols-3 gap-2 text-center"><Metric value={s.branchCount} label="Branches"/><Metric value={s.leafCount} label="Leaves"/><Metric value={s.rootStrength} label="Root score"/></div><p className="mt-4 rounded-lg bg-[#f5f7f3] p-3 text-[12px] leading-5 text-[#555]">The <b>{s.dominantCategory.toUpperCase()}</b> branch is currently dominant. {s.verifiedLeafCount} leaves are supported by verified evidence.</p></section>}function Metric({value,label}:{value:number;label:string}){return <div><b className="text-xl text-[#315f3a]">{value}</b><p className="text-[9px] uppercase tracking-wider text-[#777]">{label}</p></div>}
