"use client";
import { AnimatePresence, motion } from "framer-motion";
import { CalendarClock, ImagePlus, Laugh, Sparkles, X } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { Avatar } from "@/components/shared/avatar";
import { PolygraphPanel } from "@/components/polygraph/polygraph-panel";
import type { PolygraphResult } from "@/lib/polygraph-schema";

const statuses=["Checking for artificial humility…","Measuring corporate vocabulary…","Detecting unnecessary gratitude…","Consulting the professional theatre department…"];
export function ComposerModal({open,onClose,onPost}:{open:boolean;onClose:()=>void;onPost:(text:string)=>void}){
  const [text,setText]=useState(""); const [mode,setMode]=useState<"standard"|"polygraph">("polygraph"); const [savage,setSavage]=useState(false);
  const [result,setResult]=useState<PolygraphResult|null>(null); const [loading,setLoading]=useState(false); const [error,setError]=useState(""); const [demo,setDemo]=useState(false); const [status,setStatus]=useState(0); const lastRequest=useRef(""); const controller=useRef<AbortController|null>(null); const dialog=useRef<HTMLDivElement>(null);
  const analyse=async(value=text,force=false)=>{if(value.trim().length<25){setResult(null);setError("");setLoading(false);return}const key=`${value.trim()}::${savage}`;if(!force&&lastRequest.current===key)return;lastRequest.current=key;controller.current?.abort();controller.current=new AbortController();setLoading(true);setError("");try{const res=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({feature:"polygraph",data:{text:value,savageMode:savage}}),signal:controller.current.signal});const body=await res.json();if(!res.ok)throw new Error(body.error||"Analysis failed.");setResult(body.result);setDemo(Boolean(body.demo))}catch(e){if((e as Error).name!=="AbortError")setError(e instanceof Error?e.message:"Analysis failed.")}finally{setLoading(false)}};
  useEffect(()=>{if(mode!=="polygraph")return;const timer=setTimeout(()=>analyse(text),900);return()=>clearTimeout(timer)},[text,savage,mode]); // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!loading)return;const id=setInterval(()=>setStatus(s=>(s+1)%statuses.length),1300);return()=>clearInterval(id)},[loading]);
  useEffect(()=>{if(!open)return;const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();if(e.key==="Tab"&&dialog.current){const nodes=dialog.current.querySelectorAll<HTMLElement>('button,[href],textarea,input,[tabindex]:not([tabindex="-1"])');if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}};document.addEventListener("keydown",onKey);document.body.style.overflow="hidden";setTimeout(()=>dialog.current?.querySelector("textarea")?.focus(),50);return()=>{document.removeEventListener("keydown",onKey);document.body.style.overflow=""}},[open,onClose]);
  function close(){controller.current?.abort();onClose()}
  function post(){if(!text.trim())return;onPost(text.trim());setText("");setResult(null);lastRequest.current="";close()}
  return <AnimatePresence>{open&&<motion.div className="fixed inset-0 z-[70] grid place-items-center bg-black/50 p-0 sm:p-4" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={e=>{if(e.target===e.currentTarget)close()}}>
    <motion.div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="composer-title" className="flex max-h-[96vh] w-full max-w-[980px] flex-col overflow-hidden rounded-none bg-white shadow-2xl sm:rounded-xl" initial={{opacity:0,y:18,scale:.98}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:12,scale:.98}} transition={{duration:.18}}>
      <header className="flex items-center border-b border-[#ddd] px-5 py-3"><div><h2 id="composer-title" className="text-[18px] font-semibold">Create a post</h2><p className="text-[11px] text-[#666]">Say it professionally. Or let the machine object.</p></div><button onClick={close} className="icon-button ml-auto h-9 w-9 hover:bg-[#eee]" aria-label="Close composer"><X/></button></header>
      <div className="flex items-center gap-2 border-b border-[#eee] px-5 py-2"><button onClick={()=>setMode("polygraph")} className={`rounded-full px-3 py-1.5 text-[12px] font-bold ${mode==="polygraph"?"bg-[#191919] text-white":"bg-[#eee]"}`}><Sparkles size={13} className="mr-1 inline"/>Polygraph</button><button onClick={()=>setMode("standard")} className={`rounded-full px-3 py-1.5 text-[12px] font-bold ${mode==="standard"?"bg-[#191919] text-white":"bg-[#eee]"}`}>Standard</button><label className={`ml-auto flex items-center gap-2 text-[11px] font-semibold ${mode==="standard"?"invisible":""}`}><input type="checkbox" checked={savage} onChange={e=>setSavage(e.target.checked)} className="accent-[#B24020]"/>Savage mode</label></div>
      <div className={`min-h-0 overflow-y-auto p-4 sm:p-5 ${mode==="polygraph"?"grid gap-5 lg:grid-cols-[1fr_1.08fr]":""}`}>
        <section><div className="mb-3 flex items-center gap-3"><Avatar initials="KD" size={44}/><div><b className="text-[14px]">Khushal Dangar</b><button className="block rounded-full border border-[#777] px-2 py-0.5 text-[10px] font-semibold">🌐 Anyone ▾</button></div></div>
          <label><span className="sr-only">Post text</span><textarea value={text} onChange={e=>setText(e.target.value.slice(0,3000))} placeholder={mode==="polygraph"?"What professional truth are we dressing up today?":"What do you want to talk about?"} className="min-h-[230px] w-full resize-none border-0 bg-transparent text-[17px] leading-7 outline-none placeholder:text-[#888]"/></label>
          <div className="flex items-center justify-between border-t border-[#eee] pt-3"><div className="flex gap-1"><button className="icon-button h-9 w-9 text-[#555] hover:bg-[#eee]" title="Add media" aria-label="Add media"><ImagePlus size={20}/></button><button className="icon-button h-9 w-9 text-[#555] hover:bg-[#eee]" title="Add emoji" aria-label="Add emoji"><Laugh size={20}/></button><button className="icon-button h-9 w-9 text-[#555] hover:bg-[#eee]" title="Schedule" aria-label="Schedule"><CalendarClock size={20}/></button></div><span className={`text-[11px] ${text.length>2800?"text-[#B24020]":"text-[#777]"}`}>{text.length}/3000</span></div>
        </section>
        {mode==="polygraph"&&<PolygraphPanel result={result} loading={loading} error={error} demo={demo} status={statuses[status]} onRetry={()=>analyse(text,true)} onUse={setText}/>} 
      </div>
      <footer className="flex items-center justify-between border-t border-[#ddd] px-5 py-3"><span className="text-[11px] text-[#666]">{mode==="polygraph"?"Analysis begins after 25 characters.":"No machines are judging this draft."}</span><button onClick={post} disabled={!text.trim()} className="primary-button">Post</button></footer>
    </motion.div>
  </motion.div>}</AnimatePresence>;
}
