"use client";
import { useEffect, useState } from "react"; import { LeftSidebar } from "@/components/app-shell/left-sidebar"; import { RightSidebar } from "@/components/app-shell/right-sidebar"; import { posts as seedPosts } from "@/lib/mock-data"; import type { Post } from "@/lib/types"; import { readLocal,writeLocal } from "@/lib/local-storage"; import { PostComposer } from "./post-composer"; import { ComposerModal } from "./composer-modal"; import { PostCard } from "./post-card"; import { Toast } from "@/components/shared/toast"; import { Avatar } from "@/components/shared/avatar";
export function Feed(){const [ready,setReady]=useState(false);const [created,setCreated]=useState<Post[]>([]);const [liked,setLiked]=useState<string[]>([]);const [open,setOpen]=useState(false);const [toast,setToast]=useState("");
  // Client-only hydration is intentional: localStorage is unavailable during SSR.
  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(()=>{setCreated(readLocal("lo-created-posts",[]));setLiked(readLocal("lo-liked-posts",[]));setReady(true)},[]);
  useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(""),2600);return()=>clearTimeout(id)},[toast]);
  function addPost(content:string){const p:Post={id:`user-${Date.now()}`,author:{name:"Khushal Dangar",initials:"KD",headline:"CS & AI Student · Building products that probably did not need AI",color:"#0A66C2"},timestamp:"Now",content,likes:0,comments:0,reposts:0,sends:0,userCreated:true};const next=[p,...created];setCreated(next);writeLocal("lo-created-posts",next);setToast("Post published. The network has been informed.")}
  function like(id:string){const next=liked.includes(id)?liked.filter(x=>x!==id):[...liked,id];setLiked(next);writeLocal("lo-liked-posts",next)}
  return <><main className="shell"><div className="feed-grid"><LeftSidebar/><section aria-label="LinkedOut feed" className="min-w-0 space-y-3"><div className="card mx-0 flex items-center gap-3 p-4 md:hidden"><Avatar initials="KD" size={54}/><div><b>Khushal Dangar</b><p className="text-[12px] leading-4 text-[#666]">CS & AI Student · Building products that probably did not need AI</p></div></div><PostComposer onOpen={()=>setOpen(true)}/><div className="flex items-center gap-2 px-1 text-[10px] text-[#666]"><span className="h-px flex-1 bg-[#ccc]"/>Sort by: <b className="text-[#333]">Top ▾</b></div>{!ready?<FeedSkeleton/>:[...created,...seedPosts].map(p=><PostCard key={p.id} post={p} liked={liked.includes(p.id)} onLike={()=>like(p.id)} onToast={setToast}/>)}</section><RightSidebar/></div></main><ComposerModal open={open} onClose={()=>setOpen(false)} onPost={addPost}/><Toast message={toast} onClose={()=>setToast("")}/></>}
function FeedSkeleton(){return <>{[1,2].map(i=><div className="card animate-pulse p-4" key={i}><div className="flex gap-3"><div className="h-11 w-11 rounded-full bg-[#ddd]"/><div className="flex-1 space-y-2"><div className="h-3 w-1/3 rounded bg-[#ddd]"/><div className="h-2 w-2/3 rounded bg-[#eee]"/></div></div><div className="mt-5 h-3 rounded bg-[#eee]"/><div className="mt-2 h-3 w-4/5 rounded bg-[#eee]"/><div className="mt-4 h-28 rounded bg-[#eee]"/></div>)}</>}
