"use client";
import { useState } from "react"; import { Heart, MessageCircle, MoreHorizontal, Repeat2, Send, ThumbsUp } from "lucide-react"; import { Avatar } from "@/components/shared/avatar"; import { CommentSection } from "./comment-section"; import type { Post } from "@/lib/types";
export function PostCard({post,liked,onLike,onToast}:{post:Post;liked:boolean;onLike:()=>void;onToast:(s:string)=>void}){const [comments,setComments]=useState(false);const [share,setShare]=useState(false);return <article className="card overflow-hidden">
  <div className="flex gap-3 p-4 pb-2"><Avatar initials={post.author.initials} size={46} color={post.author.color}/><div className="min-w-0 flex-1"><h2 className="truncate text-[14px] font-semibold hover:text-[#0A66C2] hover:underline">{post.author.name}</h2><p className="truncate text-[12px] text-[#666]">{post.author.headline}</p><p className="text-[11px] text-[#777]">{post.timestamp} · 🌐</p></div><button className="self-start text-[13px] font-semibold text-[#0A66C2]">+ Follow</button><button className="icon-button h-8 w-8" aria-label="More post options"><MoreHorizontal size={19}/></button></div>
  <p className="whitespace-pre-wrap px-4 pb-3 text-[14px] leading-[20px]">{post.content}</p>
  {post.preview&&<ProjectPreview type={post.preview}/>}<div className="mx-4 flex items-center justify-between border-b border-[#eee] py-2 text-[11px] text-[#666]"><span className="flex items-center gap-1"><i className="grid h-[16px] w-[16px] place-items-center rounded-full bg-[#0A66C2] text-white"><ThumbsUp size={9} fill="white"/></i><i className="grid h-[16px] w-[16px] place-items-center rounded-full bg-[#df704d] text-white"><Heart size={9} fill="white"/></i>{post.likes+(liked?1:0)}</span><span>{post.comments} comments · {post.reposts} reposts</span></div>
  <div className="grid grid-cols-4 px-2 py-1 text-[12px] font-semibold text-[#555]">
    <Action label="Like" icon={ThumbsUp} action={onLike} active={liked}/><Action label="Comment" icon={MessageCircle} action={()=>setComments(!comments)}/><Action label="Repost" icon={Repeat2} action={()=>onToast("Reposted to your network")}/><Action label="Send" icon={Send} action={()=>setShare(!share)}/>
  </div>
  {share&&<div className="border-t border-[#eee] px-4 py-3 text-[13px]"><b>Send this post</b><div className="mt-2 flex gap-2"><button className="outline-button text-[12px]" onClick={()=>onToast("Link copied")}>Copy link</button><button className="outline-button text-[12px]" onClick={()=>onToast("Mock message started")}>New message</button></div></div>}{comments&&<CommentSection/>}
  </article>}
function Action({label,icon:Icon,action,active=false}:{label:string;icon:typeof ThumbsUp;action:()=>void;active?:boolean}){return <button onClick={action} className={`flex items-center justify-center gap-2 rounded py-2.5 hover:bg-[#eee] ${active?"text-[#0A66C2]":""}`}><Icon size={18} fill={active?"currentColor":"none"}/><span className="hidden min-[420px]:inline">{label}</span></button>}
function ProjectPreview({type}:{type:"launch"|"code"|"job"}){if(type==="code")return <div className="mx-4 mb-3 overflow-hidden rounded-lg bg-[#17212b] p-5 font-mono text-[12px] text-[#b8d7a3]"><span className="text-[#7eb6e8]">async function</span> exactlyOnce(event) &#123;<br/>　<span className="text-[#dfc184]">await</span> idempotency.check(event.id);<br/>　<span className="text-[#888]">{"// sleep better tonight"}</span><br/>&#125;</div>;if(type==="job")return <div className="mx-4 mb-3 flex items-center gap-4 rounded-lg border border-[#d7e7f7] bg-[#eef6ff] p-4"><div className="grid h-12 w-12 place-items-center rounded-lg bg-[#0A66C2] font-black text-white">N★</div><div><b className="text-[14px]">Northstar</b><p className="text-[12px] text-[#666]">A new chapter (apparently)</p></div></div>;return <div className="mx-4 mb-3 overflow-hidden rounded-lg border border-[#ddd]"><div className="flex h-[150px] items-end bg-[linear-gradient(140deg,#dbeef8,#f8dfb2)] p-5"><div><span className="rounded bg-white/90 px-2 py-1 text-[10px] font-bold text-[#0A66C2]">NOW LIVE</span><h3 className="mt-2 text-2xl font-black tracking-tight">Daybreak</h3><p className="text-[12px]">From feedback chaos to product clarity.</p></div></div></div>}
