import type { EndorsementVerdict,ProfileSkill,SkillEndorsement } from "./types";
const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
export function scoreEndorsement(e:SkillEndorsement,skill:ProfileSkill):EndorsementVerdict{
 const a=e.answers;const words=a.contributionDescription.trim().split(/\s+/).filter(Boolean).length;const projectMatch=Boolean(a.projectId&&skill.profileEvidence.some(p=>p.title.toLowerCase()===a.projectId?.toLowerCase()));
 const specificityScore=clamp(words*4+(a.projectId?24:0)+(a.evidenceDescription?15:0));const evidenceStrength=clamp((a.personallyObserved?28:4)+(projectMatch?30:a.projectId?15:0)+(a.evidenceType==="repository"||a.evidenceType==="collaboration"?26:a.evidenceType==="project"?22:a.evidenceType==="post"||a.evidenceType==="certificate"?12:0));const confidenceScore=clamp((specificityScore+evidenceStrength)/2+(a.confidence==="certain"?12:a.confidence==="fairly_certain"?5:-8));
 const status=confidenceScore>=82?"verified":confidenceScore>=65?"supported":confidenceScore>=45?"partially_supported":confidenceScore>=24?"vague":"unverified";const badges={verified:"Verified contribution",supported:"Personally witnessed",partially_supported:"Some evidence",vague:"Friendly endorsement",unverified:"No specific proof"} as const;
 const found=[a.personallyObserved&&"Direct personal observation",projectMatch&&`Profile project matched: ${a.projectId}`,a.evidenceType!=="none"&&`${a.evidenceType.replace("_"," ")} evidence supplied`,words>=10&&"Specific contribution described"].filter(Boolean) as string[];const missing=[!a.personallyObserved&&"Direct observation",!a.projectId&&"Named project",a.evidenceType==="none"&&"Supporting evidence",words<10&&"More specific contribution detail"].filter(Boolean) as string[];
 return {status,confidenceScore,evidenceStrength,specificityScore,verdictTitle:status==="verified"?"Testimony strongly supported":status==="supported"?"Supported by direct experience":status==="partially_supported"?"Some useful evidence supplied":status==="vague"?"Friendly but vague testimony":"No specific proof supplied",reasoning:found.length?`The witness supplied ${found.join(", ").toLowerCase()}. This review evaluates the submitted detail, not the witness’s honesty.`:"The endorsement is supportive, but it does not identify direct work, a project, or supporting evidence.",evidenceFound:found.slice(0,5),missingEvidence:missing.slice(0,5),witnessSummary:`${e.endorser.name} submitted a ${a.confidence.replaceAll("_"," ")} endorsement based on ${a.personallyObserved?"personally observed work":"general familiarity"}.`,badge:badges[status]};
}
