import type { NetworkAccount } from "./types";
export const NETWORK_ACCOUNTS_KEY="linkedout:network-accounts:v1";export const MESSAGE_DRAFTS_KEY="linkedout:message-drafts:v1";
const person=(name:string,headline:string,avatarInitials:string,connectionSince:string)=>({name,headline,avatarInitials,connectionSince});
export const defaultNetworkAccounts:NetworkAccount[]=[
 {id:"aarav",person:person("Aarav Sharma","Founder at Clearframe · Thoughtful introductions","AS","2024-08-12"),favoursGiven:[{id:"ag1",type:"feedback",description:"Reviewed Clearframe investor deck",date:"2026-05-04",weight:2},{id:"ag2",type:"resource",description:"Shared cohort hiring shortlist",date:"2026-06-10",weight:1}],favoursReceived:[{id:"ar1",type:"feedback",description:"Reviewed Rabbit onboarding flow",date:"2026-04-11",weight:1}],outstandingPromises:[{id:"ap1",promise:"Introduction to the design lead at Meridian",promisedAt:"2026-06-01",dueAt:"2026-06-14",status:"overdue"}],lastReplyDaysAgo:24,ignoredAskCount:2},
 {id:"ananya",person:person("Ananya Mehta","Product Designer at Daybreak","AM","2025-01-18"),favoursGiven:[{id:"ng1",type:"project_help",description:"Debugged prototype accessibility",date:"2026-06-14",weight:2}],favoursReceived:[{id:"nr1",type:"feedback",description:"Full portfolio design critique",date:"2026-06-02",weight:3},{id:"nr2",type:"resource",description:"Shared component library",date:"2026-05-20",weight:1}],outstandingPromises:[],lastReplyDaysAgo:2,ignoredAskCount:0},
 {id:"rohan",person:person("Rohan Kapoor","Software Engineer · Distributed systems","RK","2024-11-03"),favoursGiven:[{id:"rg1",type:"project_help",description:"Helped diagnose event retry bug",date:"2026-05-29",weight:2}],favoursReceived:[{id:"rr1",type:"referral",description:"Referred Khushal to AI product fellowship",date:"2026-04-17",weight:3}],outstandingPromises:[{id:"rp1",promise:"Send the architecture reading list",promisedAt:"2026-07-01",dueAt:"2026-07-20",status:"pending"}],lastReplyDaysAgo:5,ignoredAskCount:0},
 {id:"meera",person:person("Meera Iyer","Growth Lead at Northstar","MI","2025-04-22"),favoursGiven:[{id:"mg1",type:"introduction",description:"Introduced Meera to a cohort founder",date:"2026-03-09",weight:2}],favoursReceived:[{id:"mr1",type:"feedback",description:"Reviewed launch positioning",date:"2026-06-22",weight:2}],outstandingPromises:[],lastReplyDaysAgo:8,ignoredAskCount:0},
 {id:"kabir",person:person("Kabir Malhotra","Data Scientist · Reads the docs","KM","2025-09-13"),favoursGiven:[{id:"kg1",type:"resource",description:"Shared cleaned evaluation dataset",date:"2026-04-03",weight:2},{id:"kg2",type:"feedback",description:"Reviewed model evaluation notes",date:"2026-05-18",weight:1}],favoursReceived:[],outstandingPromises:[{id:"kp1",promise:"Review Astroboat evaluation approach",promisedAt:"2026-05-22",dueAt:"2026-06-02",status:"overdue"}],lastReplyDaysAgo:46,ignoredAskCount:3},
 {id:"tara",person:person("Tara Bose","UX Researcher · Asks why","TB","2026-02-07"),favoursGiven:[{id:"tg1",type:"feedback",description:"Tested interview script",date:"2026-06-25",weight:1}],favoursReceived:[{id:"tr1",type:"project_help",description:"Ran five user interviews for Life OS",date:"2026-05-10",weight:3}],outstandingPromises:[{id:"tp1",promise:"Send a written thank-you and research summary",promisedAt:"2026-06-26",dueAt:"2026-07-05",status:"pending"}],lastReplyDaysAgo:3,ignoredAskCount:0},
];
