import { Briefcase, Code2, GraduationCap, MapPin, Pencil, Sparkles } from "lucide-react";import Link from "next/link"; import { Avatar } from "@/components/shared/avatar"; import { currentUser } from "@/lib/mock-data";import { CareerPlantCard } from "@/components/career-plant/career-plant-card";import { ProfileEndorsements } from "@/components/endorsements/profile-endorsements";
const projects=["Astroboat","Rabbit","Life OS","Trial of Common Sense"];
export default function Profile(){return <main className="shell py-5 sm:py-7"><div className="mx-auto grid max-w-[1000px] gap-5 md:grid-cols-[minmax(0,680px)_280px]"><div className="space-y-4"><section className="card overflow-hidden"><div className="h-[165px] bg-[linear-gradient(120deg,#89b8dc,#d9e6d2_58%,#e8cfa9)]"/><div className="relative px-5 pb-6 sm:px-7"><div className="-mt-[70px]"><Avatar initials="KD" size={140}/></div><button className="icon-button absolute right-5 top-4 h-9 w-9 border border-[#bbb] bg-white" aria-label="Edit profile"><Pencil size={17}/></button><h1 className="mt-3 text-2xl font-bold">{currentUser.name}</h1><p className="mt-1 text-[15px]">{currentUser.headline}</p><p className="mt-2 flex items-center gap-1 text-[12px] text-[#666]"><MapPin size={13}/>{currentUser.location} · <a href="#" className="font-semibold text-[#0A66C2]">Contact info</a></p><p className="mt-3 flex items-center gap-2 text-[13px] font-semibold"><GraduationCap size={18} className="text-[#0A66C2]"/>{currentUser.university}</p><p className="mt-3 text-[13px] font-semibold text-[#0A66C2]">{currentUser.connections} connections</p><div className="mt-4 flex gap-2"><button className="primary-button">Open to</button><button className="outline-button">Add profile section</button></div></div></section><CareerPlantCard/>
  <Section title="About"><p className="text-[14px] leading-6">Interested in AI products, full-stack development, and unusual web experiences. I like building software that is useful, thoughtful, and occasionally willing to make fun of itself.</p></Section>
  <Section title="Experience"><div className="flex gap-3"><Briefcase className="mt-1 text-[#0A66C2]"/><div><h3 className="font-semibold">Student builder</h3><p className="text-[13px] text-[#666]">Independent · Present</p><p className="mt-2 text-[13px] leading-5">Building product experiments across AI, education, and personal software.</p></div></div><div className="mt-5 flex gap-3 border-t border-[#eee] pt-5"><Code2 className="mt-1 text-[#0A66C2]"/><div><h3 className="font-semibold">Content & Research Intern</h3><p className="text-[13px] text-[#666]">Previous experience</p><p className="mt-2 text-[13px] leading-5">Turned complex research into clear stories and practical product insight.</p></div></div></Section>
  <Section title="Projects"><div className="grid gap-3 sm:grid-cols-2">{projects.map((p,i)=><div key={p} className="rounded-lg border border-[#ddd] p-4"><Sparkles size={17} className="text-[#0A66C2]"/><h3 className="mt-2 font-semibold">{p}</h3><p className="mt-1 text-[12px] leading-5 text-[#666]">{["An AI navigation experiment for ambitious ideas.","A quick, curious product prototype with very long ears.","A personal operating system for less chaotic days.","An interactive experiment in reasoning and decisions."][i]}</p></div>)}</div></Section>
  <ProfileEndorsements/></div>
  <aside className="space-y-4"><section className="card p-5"><h2 className="font-semibold">Analytics</h2><p className="mt-1 text-[11px] text-[#666]">Private to you</p><div className="mt-4 grid grid-cols-2 gap-3"><Stat n={currentUser.profileViews} label="Profile views"/><Stat n={currentUser.postImpressions.toLocaleString()} label="Post impressions"/></div></section><section className="card p-5"><h2 className="font-semibold">LinkedOut experiments</h2><div className="mt-3 space-y-3 text-[12px]"><Link href="/cross-examiner" className="block hover:text-[#0A66C2]">⚖️ Review endorsement evidence</Link><Link href="/oracle" className="block hover:text-[#0A66C2]">✦ Check corporate compatibility</Link></div><p className="mt-4 text-[11px] leading-4 text-[#777]">Useful professional signals, wearing unusually elaborate costumes.</p></section></aside></div></main>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="card p-5 sm:p-7"><h2 className="mb-4 text-xl font-semibold">{title}</h2>{children}</section>}function Stat({n,label}:{n:string|number;label:string}){return <div><b className="text-xl">{n}</b><p className="text-[11px] text-[#666]">{label}</p></div>}
