import { z } from "zod";import { aiRequestSchema,polygraphResultSchema } from "@/lib/polygraph-schema";import { analyseLocally } from "@/lib/polygraph-fallback";import { careerGardenerRequestSchema,careerGardenerResultSchema } from "@/lib/career/schema";import { careerGardenerFallback } from "@/lib/career/fallback";import { debtCollectorRequestSchema,debtCollectorResultSchema } from "@/lib/network/schema";import { debtCollectorFallback } from "@/lib/network/fallback";import { runStructured } from "./groq-client";import { endorsementCrossExaminerRequestSchema } from "@/lib/endorsements/schema";import { corporateHoroscopeRequestSchema } from "@/lib/oracle/schema";import { handleEndorsementCrossExaminer } from "./endorsement-cross-examiner/handler";import { handleCorporateHoroscope } from "./corporate-horoscope/handler";
const requestSchema=z.discriminatedUnion("feature",[aiRequestSchema,careerGardenerRequestSchema,debtCollectorRequestSchema,endorsementCrossExaminerRequestSchema,corporateHoroscopeRequestSchema]);
const polygraphPrompt=`You are the Humble-Brag Polygraph in a satirical professional network. Detect fake humility, clichés, inflated language and performative gratitude. Be concise and playful, sharper only in savage mode. Never make factual claims about private intentions, attack traits, threaten, or mock hardship. Return JSON only matching the requested result shape, integer scores 0-100, maximum five phrases. Preserve the actual announcement in the honest rewrite.`;
const gardenerPrompt=`You are a perceptive, friendly professional career gardener. Interpret supplied activity and deterministic plant state. Mention specific supplied skills or project categories, identify strong and underdeveloped areas, and give exactly three practical next actions. Use one light plant metaphor. Be concise. Never predict the future, insult, shame inactivity, or use generic motivational filler. Return JSON only matching {headline,interpretation,strongestArea,neglectedArea,nextActions:[exactly 3 {title,reason,difficulty:"easy"|"medium"|"ambitious"}],gardenMetaphor}.`;
const debtPrompt=`You are a satirical professional relationship accountant. Summarise only the supplied favour history, recognise when the user owes the other person, and recommend wait, follow up, return a favour, or let it go. Draft one concise professional message matching the chosen tone. Never threaten, coerce, humiliate, invent events, imply legal or financial debt, or encourage repeated pressure. Final-notice means a respectful final check with permission to close the loop. Return JSON only matching {accountHeadline,accountSummary,recommendedAction:"follow_up"|"wait"|"return_favour"|"let_it_go",openingLine,messageDraft,humourLine,riskNote}.`;
export type RoutedResult={result:unknown;demo:boolean};
export async function routeAIFeature(body:unknown):Promise<RoutedResult>{
 const parsed=requestSchema.safeParse(body);if(!parsed.success)throw new AIRequestError("That AI request is incomplete or unsupported.");const req=parsed.data;const hasKey=Boolean(process.env.GROQ_API_KEY);
 if(req.feature==="polygraph"){const fallback=()=>analyseLocally(req.data.text,req.data.savageMode);if(!hasKey)return{result:fallback(),demo:true};try{return{result:await runStructured(polygraphPrompt,req.data,polygraphResultSchema,req.data.savageMode?.7:.45),demo:false}}catch{return{result:fallback(),demo:true}}}
 if(req.feature==="careerGardener"){const fallback=()=>careerGardenerFallback(req.data.activity,req.data.plantState);if(!hasKey)return{result:fallback(),demo:true};try{return{result:await runStructured(gardenerPrompt,req.data,careerGardenerResultSchema,.4),demo:false}}catch{return{result:fallback(),demo:true}}}
 if(req.feature==="debtCollector"){const fallback=()=>debtCollectorFallback(req.data.account,req.data.balance,req.data.tone,req.data.additionalContext);if(!hasKey)return{result:fallback(),demo:true};try{return{result:await runStructured(debtPrompt,req.data,debtCollectorResultSchema,.5),demo:false}}catch{return{result:fallback(),demo:true}}}
 if(req.feature==="endorsementCrossExaminer")return handleEndorsementCrossExaminer(req.data.skill,req.data.endorsement);
 return handleCorporateHoroscope(req.data.userProfile,req.data.preferences,req.data.company,req.data.job,req.data.compatibility);
}
export class AIRequestError extends Error{}
