import type { CompanyProfile,CorporateCompatibilityInput,JobProfile,WorkPreferences } from "./types";
type UserProfile={skills:string[];projects:Array<{name:string;category:string;description:string}>};const clamp=(n:number)=>Math.max(0,Math.min(100,Math.round(n)));
/** Scores supplied mock signals only: skills 35%, culture 25%, work style 25%, role interest 15%, minus explicit warning friction. */
export function calculateCorporateCompatibility(user:UserProfile,p:WorkPreferences,c:CompanyProfile,j:JobProfile):CorporateCompatibilityInput{
 const userSkills=user.skills.map(s=>s.toLowerCase());const matchingSkills=j.skills.filter(s=>userSkills.includes(s.toLowerCase()));const missingSkills=j.skills.filter(s=>!userSkills.includes(s.toLowerCase()));const skillMatchScore=clamp(j.skills.length?matchingSkills.length/j.skills.length*100:70);
 const aligned:string[]=[];const conflicts:string[]=[];if(c.cultureSignals.includes("remote_friendly")&&(p.remotePreference==="remote"||p.remotePreference==="flexible"))aligned.push("Remote-friendly culture");if(c.cultureSignals.includes("mentorship_focused")&&(p.learningPreference==="mentorship"||p.learningPreference==="mixed"))aligned.push("Mentorship focus");if(c.cultureSignals.includes("experimental")&&p.riskTolerance!=="low")aligned.push("Experimental environment");if(c.cultureSignals.includes("collaborative")&&p.collaborationStyle!=="independent")aligned.push("Collaborative work");if(c.cultureSignals.includes("meeting_heavy")&&p.meetingTolerance==="low")conflicts.push("Meeting-heavy culture");if(c.cultureSignals.includes("fast_paced")&&p.pace==="steady")conflicts.push("Faster preferred pace");if(c.cultureSignals.includes("process_heavy")&&p.structurePreference==="flexible")conflicts.push("Process-heavy environment");if(j.workplace!==p.remotePreference&&p.remotePreference!=="flexible")conflicts.push(`${j.workplace.replace("_","-")} workplace`);
 const cultureMatchScore=clamp(68+aligned.length*10-conflicts.length*13);const workStyleMatchScore=clamp(72+j.workStyleSignals.filter(s=>s.includes(p.collaborationStyle)||s.includes(p.pace)||s.includes(p.learningPreference)).length*7-conflicts.length*9);const interestWords=user.projects.map(x=>`${x.category} ${x.description}`).join(" ").toLowerCase();const roleInterestScore=clamp(55+j.skills.filter(s=>interestWords.includes(s.toLowerCase().split(" ")[0])).length*12);const warningPenalty=Math.min(30,clamp(j.warningSignals.length*4+c.riskSignals.length*2+conflicts.length*5));const preliminaryScore=clamp(skillMatchScore*.35+cultureMatchScore*.25+workStyleMatchScore*.25+roleInterestScore*.15-warningPenalty);
 return {skillMatchScore,cultureMatchScore,workStyleMatchScore,roleInterestScore,warningPenalty,preliminaryScore,matchingSkills,missingSkills,alignedSignals:aligned,conflictingSignals:conflicts};
}
