import type { CompanyProfile,JobProfile,WorkPreferences } from "./types";
export const WORK_PREFERENCES_KEY="linkedout:work-preferences:v1";export const CORPORATE_READINGS_KEY="linkedout:corporate-readings:v1";export const ORACLE_HISTORY_KEY="linkedout:oracle-history:v1";
export const defaultWorkPreferences:WorkPreferences={pace:"fast",meetingTolerance:"low",structurePreference:"balanced",collaborationStyle:"small_team",riskTolerance:"medium",learningPreference:"mixed",remotePreference:"flexible"};
export const companies:CompanyProfile[]=[
 {id:"nebula",name:"Nebula Labs",industry:"AI products",size:"startup",description:"Builds practical AI tools for small creative teams.",logoInitials:"NL",cultureSignals:["fast_paced","high_ownership","experimental","collaborative"],publicValues:["Ship useful things","Write down decisions"],riskSignals:["Ambiguous scope","Frequent priority changes"],positiveSignals:["Direct founder access","Real user feedback"]},
 {id:"orbit",name:"Orbit Systems",industry:"Developer infrastructure",size:"mid_size",description:"Infrastructure for teams operating distributed applications.",logoInitials:"OS",cultureSignals:["structured","remote_friendly","independent","mentorship_focused"],publicValues:["Reliable systems","Calm communication"],riskSignals:["Long review cycles"],positiveSignals:["Strong mentorship","Documented engineering"]},
 {id:"paperclip",name:"Paperclip AI",industry:"Workflow automation",size:"small",description:"Automates repetitive operations for growing companies.",logoInitials:"PA",cultureSignals:["fast_paced","meeting_heavy","experimental","deadline_driven"],publicValues:["Default to action","Customer obsession"],riskSignals:["Dense calendars","Aggressive deadlines"],positiveSignals:["Broad ownership","Fast learning"]},
 {id:"monolith",name:"Monolith Finance",industry:"Financial technology",size:"large",description:"Builds regulated financial platforms at considerable scale.",logoInitials:"MF",cultureSignals:["structured","process_heavy","competitive","meeting_heavy"],publicValues:["Precision","Risk awareness"],riskSignals:["Process density","Slow experimentation"],positiveSignals:["Clear progression","Deep specialist teams"]},
 {id:"greenroom",name:"Greenroom Studio",industry:"Digital product design",size:"small",description:"A collaborative studio for thoughtful consumer products.",logoInitials:"GS",cultureSignals:["collaborative","remote_friendly","experimental","mentorship_focused"],publicValues:["Craft with context","Invite critique"],riskSignals:["Client-driven changes"],positiveSignals:["Design mentorship","Flexible working"]},
 {id:"northstar",name:"Northstar Robotics",industry:"Robotics",size:"mid_size",description:"Software and sensing systems for warehouse robotics.",logoInitials:"NR",cultureSignals:["high_ownership","deadline_driven","collaborative","structured"],publicValues:["Safety first","Learn from hardware"],riskSignals:["On-site testing windows"],positiveSignals:["Cross-functional work","Tangible impact"]},
 {id:"quietstack",name:"QuietStack",industry:"Developer tools",size:"startup",description:"Low-noise observability tools for independent engineering teams.",logoInitials:"QS",cultureSignals:["remote_friendly","independent","experimental","high_ownership"],publicValues:["Fewer meetings","Deep work"],riskSignals:["Limited formal mentorship"],positiveSignals:["Async by default","Small focused teams"]},
 {id:"sprintforge",name:"SprintForge",industry:"Product consulting",size:"mid_size",description:"Rapid product delivery for ambitious enterprise teams.",logoInitials:"SF",cultureSignals:["fast_paced","deadline_driven","meeting_heavy","competitive"],publicValues:["Deliver weekly","Own the outcome"],riskSignals:["High context switching","Calendar density"],positiveSignals:["Varied projects","Visible responsibility"]},
];
export const jobs:JobProfile[]=[
 {id:"neb-ai",companyId:"nebula",title:"AI Product Intern",location:"Bengaluru, India",workplace:"hybrid",experienceLevel:"internship",skills:["Python","AI Integration","Product Design"],responsibilities:["Prototype AI workflows","Run user tests"],workStyleSignals:["small_team","experimental","fast"],warningSignals:["ambiguous scope"],salaryLabel:"₹35k–50k / month",postedDaysAgo:2},
 {id:"neb-fe",companyId:"nebula",title:"Frontend Engineering Intern",location:"Remote, India",workplace:"remote",experienceLevel:"internship",skills:["TypeScript","Next.js","Product Design"],responsibilities:["Build product surfaces","Improve design system"],workStyleSignals:["small_team","high ownership"],warningSignals:["changing priorities"],postedDaysAgo:5},
 {id:"orbit-full",companyId:"orbit",title:"Junior Full-Stack Developer",location:"Delhi, India",workplace:"hybrid",experienceLevel:"entry",skills:["TypeScript","Next.js","Python","Databases"],responsibilities:["Ship platform features","Maintain APIs"],workStyleSignals:["structured","mentorship"],warningSignals:["long reviews"],salaryLabel:"₹8–12 LPA",postedDaysAgo:4},
 {id:"orbit-devrel",companyId:"orbit",title:"Developer Relations Intern",location:"Remote",workplace:"remote",experienceLevel:"internship",skills:["TypeScript","Technical Writing","Public Speaking"],responsibilities:["Create technical guides","Support community demos"],workStyleSignals:["independent","remote"],warningSignals:[],postedDaysAgo:8},
 {id:"paper-applied",companyId:"paperclip",title:"Applied AI Intern",location:"Bengaluru, India",workplace:"on_site",experienceLevel:"internship",skills:["Python","AI Integration","Evaluation"],responsibilities:["Build customer automations","Evaluate prompts"],workStyleSignals:["intense","fast"],warningSignals:["meeting heavy","tight deadlines"],postedDaysAgo:1},
 {id:"paper-product",companyId:"paperclip",title:"Product Design Intern",location:"Bengaluru, India",workplace:"hybrid",experienceLevel:"internship",skills:["Product Design","User Research","Prototyping"],responsibilities:["Map workflows","Test prototypes"],workStyleSignals:["collaborative","fast"],warningSignals:["calendar density"],postedDaysAgo:6},
 {id:"mono-back",companyId:"monolith",title:"Backend Engineering Intern",location:"Mumbai, India",workplace:"on_site",experienceLevel:"internship",skills:["Python","Databases","APIs"],responsibilities:["Build internal services","Write tests"],workStyleSignals:["structured","process"],warningSignals:["process heavy"],postedDaysAgo:9},
 {id:"green-design",companyId:"greenroom",title:"Product Design Intern",location:"Remote, India",workplace:"remote",experienceLevel:"internship",skills:["Product Design","User Research","Figma"],responsibilities:["Support research","Prototype interactions"],workStyleSignals:["collaborative","mentorship"],warningSignals:["client changes"],postedDaysAgo:3},
 {id:"north-research",companyId:"northstar",title:"Research Engineering Intern",location:"Pune, India",workplace:"on_site",experienceLevel:"internship",skills:["Python","AI Integration","Research"],responsibilities:["Test perception models","Build evaluation tools"],workStyleSignals:["structured","cross functional"],warningSignals:["hardware deadlines"],postedDaysAgo:7},
 {id:"quiet-fe",companyId:"quietstack",title:"Frontend Engineering Intern",location:"Remote",workplace:"remote",experienceLevel:"internship",skills:["TypeScript","Next.js","Accessibility"],responsibilities:["Build observability UI","Improve performance"],workStyleSignals:["independent","deep work"],warningSignals:["limited mentorship"],postedDaysAgo:2},
 {id:"quiet-devrel",companyId:"quietstack",title:"Developer Relations Intern",location:"Remote",workplace:"remote",experienceLevel:"internship",skills:["Technical Writing","TypeScript","Community"],responsibilities:["Write launch guides","Build examples"],workStyleSignals:["independent","async"],warningSignals:[],postedDaysAgo:11},
 {id:"sprint-full",companyId:"sprintforge",title:"Associate Product Engineer",location:"Gurugram, India",workplace:"hybrid",experienceLevel:"associate",skills:["TypeScript","Next.js","Product Design","APIs"],responsibilities:["Deliver client products","Lead weekly demos"],workStyleSignals:["intense","highly collaborative"],warningSignals:["deadline density","context switching"],salaryLabel:"₹10–14 LPA",postedDaysAgo:4},
];
